Post Balances
Granola-Team/mina-indexer pull request #126
Opened 2023-06-28 23:41 UTC by jenr24G

Changes our Ledger to use the Post Balances on each block to calculate account balances and nonces. This does not use the staged ledger diff Post Balance for the Coinbase Rewards, Transaction Fees, and Snark Worker Fees, which could be a bug in how MinaExplorer and the Archive Node calculate their balances, since this branch matches their balances exactly.

* create `UserCommand` type for the Post Balances
* create `Ledger::apply_post_balances`
* create `tests::state::ledger::apply_post_balances`

<hr>

Relevant Asana Tasks:

* https://app.asana.com/0/1203669416123378/1203770209987818/f
* https://app.asana.com/0/1203669416123378/1204886108856178/f

2023-06-29 01:18 UTC, Isaac-DeFrain reviewed
See comments

2023-06-29 01:18 UTC, Isaac-DeFrain commented on src/state/mod.rs
> +            // QUESTION: Prune blocks that create a dangling branch?
I think the only way to do this in general is to check each block to see if it's parent exists in the db. If not, that's a problem and we can disregard it. If so, we could backtrack and count the length or break once we find an ancestor with a length or without a parent. Either way, I think it's splitting hairs...

2023-06-29 01:18 UTC, Isaac-DeFrain commented on src/store.rs
> +    pub fn iterator(&self) -> DBIteratorWithThreadMode<DBWithThreadMode<MultiThreaded>> {
I'm questioning if this is necessary

2023-06-29 14:50 UTC, mxnnn submitted a review, later dismissed

2023-06-29 16:34 UTC, jenr24G commented on src/state/mod.rs
> +        debug!("finding best tip in the provided database");
I agree with this now. It's pointless to write the algorithm to find these values when we can just include them in the snapshot

2023-06-29 19:29 UTC, Isaac-DeFrain commented on src/state/mod.rs
> +        check_if_block_in_db: bool,
I think we need this (or something else to achieve the same goal) for how we are doing the restoration from db. We need a way to distinguish between when we're adding blocks to the db and not

2023-06-29 19:30 UTC, Isaac-DeFrain commented on src/state/mod.rs
> +        check_if_block_in_db: bool,
But it can certainly be taken out of this "post balances" PR!

2023-06-29 19:33 UTC, Isaac-DeFrain commented
Can we get rid of the `Error::default()` thing in `src/state/ledger/mod.rs#L122`? Clippy is constantly complaining about it

2023-07-02 17:38 UTC, jenr24G commented on src/state/mod.rs
> +            // QUESTION: Prune blocks that create a dangling branch?
let's move this to an issue @Isaac-DeFrain

2023-07-02 17:42 UTC, jenr24G commented
> Can we get rid of the `Error::default()` thing in `src/state/ledger/mod.rs#L122`? Clippy is constantly complaining about it

Jason fixed this!

2023-07-05 18:15 UTC, trevorbernard approved these changes

2023-07-05 18:20 UTC, trevorbernard requested changes
There are some merge conflicts

2023-07-05 20:53 UTC, Isaac-DeFrain reviewed
Some minor comments. Otherwise, LGTM!

2023-07-05 20:53 UTC, Isaac-DeFrain commented on src/state/ledger/mod.rs
> +    pub fn apply_delegation(&mut self, delegator: PublicKey, new_delegate: PublicKey) {
Why even check the old delegate if the outcome is the same either way?

2023-07-05 20:53 UTC, Isaac-DeFrain commented on src/state/ledger/mod.rs
> +            let nonce = if let Some(nonce) = nonce {
Why not just conditionally set the nonce?

2023-07-05 20:53 UTC, Isaac-DeFrain commented on src/state/ledger/user_commands.rs
> +                let source_nonce = match &command.data.t.t {
All these `.t`s are gross! Maybe we can isolate all these accessors nicely into their own functions?

2023-07-05 20:53 UTC, Isaac-DeFrain commented on src/state/ledger/user_commands.rs
> +                        signed_command.t.t.payload.t.t.common.t.t.t.nonce.t.t
`signed_command.payload().nonce()` would be so much nicer!

2023-07-05 20:53 UTC, Isaac-DeFrain commented on src/state/ledger/user_commands.rs
> +                                signed_command.t.t.payload.t.t.common.t.t.t.fee_payer_pk;
`signed_command.payload().fee_payer_pk()` would be so much nicer!

2023-07-05 20:53 UTC, Isaac-DeFrain commented on src/state/ledger/user_commands.rs
> +                            match signed_command.t.t.payload.t.t.body.t.t {
`signed_command.payload().body()`

2023-07-05 20:53 UTC, Isaac-DeFrain commented on src/state/ledger/user_commands.rs
> +        precomputed_block
Maybe `precomputed_block.commands()`?

2023-07-06 03:29 UTC, Isaac-DeFrain commented on src/state/ledger/user_commands.rs
> +                let source_nonce = match &command.data.t.t {
I mostly took care of this

2023-07-06 17:26 UTC, Isaac-DeFrain approved these changes
LGTM! But @mxnnn and @trevorbernard need to approve since they requested changes

2023-07-06 18:33 UTC, trevorbernard approved these changes

2023-07-06 18:37 UTC, merged