tests
Granola-Team/mina-indexer pull request #127
Opened 2023-06-29 04:13 UTC by jstavh

more tests

2023-06-29 19:37 UTC, Isaac-DeFrain reviewed
LGTM!
Can you include a test comparing the `AccountDiff` from a block against the post balance calculation? I suggest using the genesis ledger and block 2 (as long as it has payments in it). We don't need to check all balances, just one that interacts with a payment should do

2023-06-29 22:24 UTC, jenr24G requested changes
Looks great! I agree with Isaac about using the post balances as a source of truth! Can you fix the clippy warning? Thanks!

2023-06-30 14:16 UTC, jstavh commented
@Isaac-DeFrain @jenr24G To keep our PR's small, let's merge this one since you both think it looks good and then make a separate PR for the test you mention and also one for the `from_block_fees` function?

2023-06-30 20:43 UTC, Isaac-DeFrain commented on src/state/ledger/diff/account.rs
> +        let expected_account_diff = AccountDiff::Payment(expected_payment_diff);
Interesting. This could explain why our nonces were off.

2023-06-30 20:43 UTC, Isaac-DeFrain commented on src/state/ledger/mod.rs
> +                None => {
How does this work with the creation of a new account?

2023-06-30 21:25 UTC, Isaac-DeFrain approved these changes

2023-06-30 21:25 UTC, Isaac-DeFrain commented on src/state/ledger/diff/account.rs
> +        let expected_account_diff = AccountDiff::Payment(expected_payment_diff);
We're processing coinbases as payments? Payments should increase the nonce, but I don't think coinbases should. Not sure. Just a thought.

2023-06-30 22:34 UTC, jenr24G approved these changes

2023-06-30 22:34 UTC, merged