Use zstd in speedb
Granola-Team/mina-indexer pull request #606
Opened 2024-03-13 21:45 UTC by robinbb

2024-03-13 22:16 UTC, trevorbernard commented
@robinbb, you'll need to modify the speed::Options in the new method in the store to use compression.

https://github.com/Granola-Team/mina-indexer/blob/acb097016db7eae938544f306644f4e1b9bd6bd3/src/store.rs#L59

https://github.com/Granola-Team/mina-indexer/blob/acb097016db7eae938544f306644f4e1b9bd6bd3/src/store.rs#L70

```rust
let mut cf_opts = Options::default();
cf_opts.set_compression_type(DBCompressionType::Zstd);
```

2024-03-13 23:14 UTC, robinbb commented
Please squash merge.

2024-03-13 23:25 UTC, trevorbernard requested changes
You forgot to enable compression for this Option
https://github.com/Granola-Team/mina-indexer/blob/acb097016db7eae938544f306644f4e1b9bd6bd3/src/store.rs#L70

2024-03-14 00:29 UTC, trevorbernard approved these changes

2024-03-14 00:29 UTC, merged